import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Providers } from "./providers";
import "./globals.css";
import { ClientToaster } from "./ClientToaster";

import { Sidebar } from "@/features/ui/Sidebar";
import { GlobalShortcuts } from "@/features/ui/GlobalShortcuts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="h-dvh overflow-hidden flex">
        {/* Set the theme before first paint: saved choice, else OS preference.
            Landing dark-preferring users on "dark" also opts them out of
            the browser's force-dark inversion (color-scheme: dark). */}
        <script
          dangerouslySetInnerHTML={{
            __html: `!function(){try{var k="theme",t=localStorage.getItem(k);if(t!=="light"&&t!=="dark"){t=matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light";localStorage.setItem(k,t)}document.documentElement.dataset.theme=t}catch(e){document.documentElement.dataset.theme="light"}}()`,
          }}
        />
        <Providers>
          <>
            <GlobalShortcuts />
            <Sidebar />
            <main
              id="main-content"
              tabIndex={-1}
              className="h-dvh overflow-auto flex-1 focus:outline-none"
            >
              {children}
            </main>
          </>
          <ClientToaster />
        </Providers>
      </body>
    </html>
  );
}
