// Semantic icon names — the app imports from here, not from lucide directly.
// To swap an icon, change only the right-hand side; call sites stay the same.
export {
  LogOut,
  Car,
  Truck,
  Sun as LightTheme,
  Moon as DarkTheme,
  Check as Confirm,
  X as Cancel,
  Search as Lookup,
  SlidersHorizontal as Filter,
  Send as Notify,
  ArrowLeft as Back,
  ChevronDown,
  ChevronLeft as Prev,
  ChevronRight as Next,
  ChevronRight,
  Plus,
  PanelRightOpen as OpenWorkspaceOverlay,
  ClipboardList as Inspection,
  Fuel,
  Settings as Transmission,
  Armchair as Seat,
  Mail,
  LockKeyhole as Lock,
} from "lucide-react";
